### ISSUE TITLE
Fast switching of streams/tracks for large conferences / Third Room etc.

### ISSUE THREAD

**Issue by Sean-Der** [matrix-org/sfu-to-sfu#4] opened 2022-05-26 17:46 UTC

**Comment by SimonBrandner** [comment] 2022-08-12 09:01
Related https://github.com/matrix-org/sfu-to-sfu/issues/15

**Comment by SimonBrandner** [comment] 2022-08-25 13:18
Duplicate of https://github.com/matrix-org/sfu-to-sfu/issues/15

(actually)

**Closed by SimonBrandner** 2022-08-25 13:18 UTC
Labels: T-Enhancement
